
#GitHub Actions YAML for .NET Core 2.2
name: Build and Dockerize .NET Core App

# Trigger pipeline on push or pull request to main and develop branches
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Define the build job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.2.x

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore aspnet-core-dotnet-core.sln

      # Build the project
      - name: Build Project
        run: dotnet build aspnet-core-dotnet-core.sln --configuration Release --no-restore

      # Test the project (optional, if tests are available)
      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      # Publish the project
      - name: Publish Project
        run: dotnet publish aspnet-core-dotnet-core/aspnet-core-dotnet-core.csproj --configuration Release --output ./publish

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t my-dotnet-app .

      # Push Docker image to AWS ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1 # Replace with your AWS region

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker Image
        run: |
          docker tag my-dotnet-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/my-dotnet-app:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-1.amazonaws.com/my-dotnet-app:latest

